# https://pre-commit.com/

repos:
  - repo: local
    hooks:
      - id: fix
        name: fix
        language: system
        files: '[.]rs$'
        pass_filenames: false
        entry: cargo fix --allow-staged

      - id: fmt
        name: fmt
        language: system
        files: '[.]rs$'
        entry: rustup run --install nightly-2021-03-25 rustfmt

      - id: check
        name: check
        language: system
        files: '[.]rs$'
        pass_filenames: false
        entry: cargo clippy --all-targets --features strict

      - id: test
        name: test
        language: system
        files: '[.]rs$'
        pass_filenames: false
        entry: cargo test
