# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI
on: [push, pull_request]
jobs:
  fmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          profile: minimal
          components: rustfmt
          override: true
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          override: true
      - run: cargo clippy --locked --all-targets --features strict

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - run: cargo --locked test
